### ISSUE TITLE
fps/ms counter is gray

### ISSUE THREAD

**Issue by Fugaz1** [zanony/Broker_MicroMenu#1]
https://github.com/zanony/Broker_MicroMenu/blob/master/Broker_MicroMenu.lua#L89
cff808080 is gray, should be cff00ff00 (green)

**Comment by Kiatra** [comment]
Why should it be green? I deliberately changed it from green to gray.

**Comment by Kiatra** [comment]
I made the change. You may need to enable coloring as it now is off per default.

**Comment by Fugaz1** [comment]
Checked 1.6 works fine now, thanks.
