### ISSUE TITLE
CallbackHandler-1.0 is not included in libs.xml

### ISSUE THREAD

**Issue by KyrosKrane** [zanony/Broker_MicroMenu#2]
The library CallbackHandler-1.0 is bundled with Broker_MicroMenu, but it is not actually included in libs\libs.xml. This causes errors if you load BMM with a broker display that loads after BMM, even if the display loads CallbackHandler itself.

The fix is to add this line into libs\libs.xml at line 5, after LibStub:

`  <Include file="CallbackHandler-1.0\CallbackHandler-1.0.xml" />`

Note that if you have another addon that uses CallbackHandler and loads before BMM, it would hide this error, as that other addon would have loaded CallbackHandler before BMM tried to use it.

**Comment by Kiatra** [comment]
Fixed in v1.7.6
