### ISSUE TITLE
10.0 update needed - now completely broken

### ISSUE THREAD

**Issue by dblanch369** [zanony/Broker_MicroMenu#5]
10.0 update needed - now completely broken.  In 9.x, it worked, but in 10.0 you get a LUA error when hovering over.   I have also updated Titan to it's 10.0 version.  And Broker_MicroMenu DOES show fps/pings as expected, you just can't interact with menu, it just gives the LUA error.  Here is the error I am getting: 

10x ...terface/AddOns/Broker_MicroMenu/Broker_MicroMenu.lua:280: attempt to index field 'GameMenuButtonOptions' (a nil value)
[string "@Interface/AddOns/Broker_MicroMenu/Broker_MicroMenu.lua"]:280: in function <...terface/AddOns/Broker_MicroMenu/Broker_MicroMenu.lua:157>
[string "@Interface/AddOns/Titan/LDBToTitan.lua"]:344: in function <Interface/AddOns/Titan/LDBToTitan.lua:303>

Locals:
self = TitanPanelBroker_MicroMenuButton {
 0 = <userdata>
 registry = <table> {
 }
 tooltip = Frame {
 }
}
y = 1
x = 1
ckey = "C"
y = 2
x = 1
key = "P"
y = 3
x = 1
y = 4
x = 1
y = 5
x = 1
y = 6
x = 1
y = 7
x = 1
y = 11
x = 1
y = 13
x = 1
(*temporary) = <function> defined @Interface/AddOns/Decursive/Libs/LibQTip-1.0/LibQTip-1.0.lua:1295
(*temporary) = Frame {
 0 = <userdata>
 OnBackdropLoaded = <function> defined @Interface/AddOns/Blizzard_Deprecated/Deprecated_9_1_5.lua:12
 GetBackdropColor = <function> defined @Interface/SharedXML/SharedTooltipTemplates.lua:191
 key = "Broker_MicroMenuTooltip"
 SetBackdropBorderColor = <function> defined @Interface/SharedXML/SharedTooltipTemplates.lua:195
 scrollChild = Frame {
 }
 ApplyBackdrop = <function> defined @Interface/AddOns/Blizzard_Deprecated/Deprecated_9_1_5.lua:22
 SetBackdrop = <function> defined @Interface/AddOns/Blizzard_Deprecated/Deprecated_9_1_5.lua:27
 ClearBackdrop = <function> defined @Interface/AddOns/Blizzard_Deprecated/Deprecated_9_1_5.lua:34
 GetBackdropBorderColor = <function> defined @Interface/SharedXML/SharedTooltipTemplates.lua:199
 GetBackdrop = <function> defined @Interface/AddOns/Blizzard_Deprecated/Deprecated_9_1_5.lua:19
 height = 224
 SetBorderBlendMode = <function> defined @Interface/SharedXML/SharedTooltipTemplates.lua:203
 regularFont = GameTooltipText {
 }
 layoutType = "TooltipDefaultLayout"
 headerFont = GameTooltipHeaderText {
 }
 SetupTextureCoordinates = <function> defined @Interface/AddOns/Blizzard_Deprecated/Deprecated_9_1_5.lua:16
 GetBackdropCoordValue = <function> defined @Interface/AddOns/Blizzard_Deprecated/Deprecated_9_1_5.lua:15
 HasBackdropInfo = <function> defined @Interface/AddOns/Blizzard_Deprecated/Deprecated_9_1_5.lua:18
 scrollFrame = ScrollFrame {
 }
 lines = <table> {
 }
 GetEdgeSize = <function> defined @Interface/AddOns/Blizzard_Deprecated/Deprecated_9_1_5.lua:14
 NineSlice = Frame {
 }
 columns = <table> {
 }
 colspans = <table> {
 }
 TooltipBackdropOnLoad = <function> defined @Interface/SharedXML/SharedTooltipTemplates.lua:172
 width = 170.132477
 labelProvider = <table> {
 }
 SetupPieceVisuals = <function> defined @Interface/AddOns/Blizzard_Deprecated/Deprecated_9_1_5.lua:17
 SetBackdropColor = <function> defined @Interface/SharedXML/SharedTooltipTemplates.lua:187
 OnBackdropSizeChanged = <function> defined @Interface/AddOns/Blizzard_Deprecated/Deprecated_9_1_5.lua:13
}
(*temporary) = 13
(*temporary) = 2
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = Frame {
 0 = <userdata>
 OnBackdropLoaded = <function> defined @Interface/AddOns/Blizzard_Deprecated/Deprecated_9_1_5.lua:12
 GetBackdropColor = <function> defined @Interface/SharedXML/SharedTooltipTemplates.lua:191
 key = "Broker_MicroMenuTooltip"
 SetBackdropBorderColor = <function> defined @Interface/SharedXML/SharedTooltipTemplates.lua:195
 scrollChild = Frame {
 }
 ApplyBackdrop = <function> defined @Interface/AddOns/Blizzard_Deprecated/Deprecated_9_1_5.lua:22
 SetBackdrop = <function> defined @Interface/AddOns/Blizzard_Deprecated/Deprecated_9_1_5.lua:27
 ClearBackdrop = <function> defined @Interface/AddOns/Blizzard_Deprecated/Deprecated_9_1_5.lua:34
 GetBackdropBorderColor = <function> defined @Interface/SharedXML/SharedTooltipTemplates.lua:199
 GetBackdrop = <function> defined @Interface/AddOns/Blizzard_Deprecated/Deprecated_9_1_5.lua:19
 height = 224
 SetBorderBlendMode = <function> defined @Interface/SharedXML/SharedTooltipTemplates.lua:203
 regularFont = GameTooltipText {
 }
 layoutType = "TooltipDefaultLayout"
 headerFont = GameTooltipHeaderText {
 }
 SetupTextureCoordinates = <function> defined @Interface/AddOns/Blizzard_Deprecated/Deprecated_9_1_5.lua:16
 GetBackdropCoordValue = <function> defined @Interface/AddOns/Blizzard_Deprecated/Deprecated_9_1_5.lua:15
 HasBackdropInfo = <function> defined @Interface/AddOns/Blizzard_Deprecated/Deprecated_9_1_5.lua:18
 scrollFrame = ScrollFrame {
 }
 lines = <table> {
 }
 GetEdgeSize = <function> defined @Interface/AddOns/Blizzard_Deprecated/Deprecated_9_1_5.

**Comment by Kiatra** [comment]
Fixed with the latest version

**Comment by dblanch369** [comment]
Thank you very much!!!
